<hr size="3" width="100%" color="#435e70">
<center>This paged best viewed with <a href="http://www.microsoft.com/windows/ie"><img src="../gfx/buttons/ie.jpg" width="22" height="22" border="0" alt="Internet Explorer"></a> at 800x600 screen resolution.<br>
If you have a problem viewing this site please contact <a href="mailto:aztek@nether.net">AZTEK</a>.<center>
<a href="../copyright.php">Copyright &copy;</a>2001 Caffeinated Data Phreaks<br>
</center>
</td></tr>
</table>
</body>
</html>